name: docker-build
description: "Composite action to build and push a Docker target to GHCR"
inputs:
  target:
    description: "Dockerfile target stage to build"
    required: true
  tag:
    description: "Image tag to push"
    required: true
  freespace:
    description: "Remove large pre‑installed SDKs before building to free space"
    required: false
    default: "false"
  context:
    description: "Docker build context"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Free up disk space
      if: ${{ inputs.freespace == 'true' }}
      shell: bash
      run: |
        echo -e "pre cleanup space:\n $(df -h)"
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/lib/android
        echo -e "post cleanup space:\n $(df -h)"

    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - uses: crazy-max/ghaction-github-runtime@v3

    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        install: true
        use: true

    - name: Build & Push ${{ inputs.target }}
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ${{ inputs.context }}
        file: docker/${{ inputs.target }}/Dockerfile
        tags: ghcr.io/dimensionalos/${{ inputs.target }}:${{ inputs.tag }}
        cache-from: type=gha,scope=${{ inputs.target }}
        cache-to: type=gha,mode=max,scope=${{ inputs.target }}
        build-args: |
          FROM_TAG=${{ inputs.tag }}
